# Generated by Django 5.1.7 on 2025-03-20 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Articulos",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_publicacion", models.DateField()),
                ("doi", models.CharField(blank=True, max_length=100, null=True)),
                ("url", models.CharField(blank=True, max_length=200, null=True)),
                ("nombre", models.CharField(max_length=200)),
                ("nombre_revista", models.CharField(max_length=200)),
                (
                    "pais_publicacion",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("anio_publicacion", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "articulos",
            },
        ),
        migrations.CreateModel(
            name="Carreras",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "carreras",
            },
        ),
        migrations.CreateModel(
            name="Herramientas",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("descripcion", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "herramientas",
            },
        ),
        migrations.CreateModel(
            name="Investigador",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                ("correo", models.CharField(max_length=100, unique=True)),
                ("sueldo", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "db_table": "investigador",
            },
        ),
        migrations.CreateModel(
            name="Lineas",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("descripcion", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "lineas",
            },
        ),
        migrations.CreateModel(
            name="NivelSnii",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("descripcion", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "nivel_snii",
            },
        ),
        migrations.CreateModel(
            name="Proyectos",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=200)),
                ("fecha_inicio", models.DateField()),
                ("fecha_termino", models.DateField()),
                ("ingresos", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "db_table": "proyectos",
            },
        ),
        migrations.CreateModel(
            name="TipoEstudiante",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("descripcion", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "tipo_estudiante",
            },
        ),
        migrations.CreateModel(
            name="TipoEvento",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("descripcion", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "tipo_evento",
            },
        ),
        migrations.CreateModel(
            name="Usuarios",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "usuarios",
            },
        ),
        migrations.CreateModel(
            name="Snii",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_asignacion", models.DateField()),
                (
                    "investigador",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.investigador",
                    ),
                ),
                (
                    "nivel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.nivelsnii",
                    ),
                ),
            ],
            options={
                "db_table": "snii",
            },
        ),
        migrations.CreateModel(
            name="Estudiante",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("escuela", models.CharField(max_length=100)),
                ("fecha_inicio", models.DateField()),
                ("fecha_termino", models.DateField()),
                ("sueldo", models.DecimalField(decimal_places=2, max_digits=10)),
                ("nombre", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "carrera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.carreras",
                    ),
                ),
                (
                    "investigador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.investigador",
                    ),
                ),
                (
                    "tipo_estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.tipoestudiante",
                    ),
                ),
            ],
            options={
                "db_table": "estudiante",
            },
        ),
        migrations.CreateModel(
            name="Eventos",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=200)),
                ("lugar", models.CharField(max_length=100)),
                ("fecha", models.DateField()),
                ("duracion", models.IntegerField()),
                ("empresa_invita", models.CharField(max_length=200)),
                (
                    "tipo_evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.tipoevento",
                    ),
                ),
            ],
            options={
                "db_table": "eventos",
            },
        ),
        migrations.CreateModel(
            name="DetEventos",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.eventos",
                    ),
                ),
                (
                    "investigador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.investigador",
                    ),
                ),
            ],
            options={
                "db_table": "det_eventos",
                "unique_together": {("investigador", "evento")},
            },
        ),
        migrations.CreateModel(
            name="DetArt",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("es_principal", models.BooleanField(blank=True, null=True)),
                (
                    "articulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.articulos",
                    ),
                ),
                (
                    "investigador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.investigador",
                    ),
                ),
            ],
            options={
                "db_table": "det_art",
                "unique_together": {("investigador", "articulo")},
            },
        ),
        migrations.CreateModel(
            name="DetLineas",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "investigador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.investigador",
                    ),
                ),
                (
                    "linea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gestion.lineas"
                    ),
                ),
            ],
            options={
                "db_table": "det_lineas",
                "unique_together": {("investigador", "linea")},
            },
        ),
        migrations.CreateModel(
            name="DetProy",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("es_principal", models.BooleanField(blank=True, null=True)),
                (
                    "investigador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.investigador",
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.proyectos",
                    ),
                ),
            ],
            options={
                "db_table": "det_proy",
                "unique_together": {("investigador", "proyecto")},
            },
        ),
        migrations.CreateModel(
            name="DetHerr",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "herramienta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.herramientas",
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.proyectos",
                    ),
                ),
            ],
            options={
                "db_table": "det_herr",
                "unique_together": {("proyecto", "herramienta")},
            },
        ),
    ]
