# Generated by Django 5.1.7 on 2025-03-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estudiante",
            name="sueldo",
            field=models.DecimalField(decimal_places=2, default=3200.0, max_digits=10),
        ),
    ]
