# Generated by Django 5.1.7 on 2025-04-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0002_alter_estudiante_sueldo"),
    ]

    operations = [
        migrations.AddField(
            model_name="proyectos",
            name="duracion_estimada",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="proyectos",
            name="duracion_real",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="proyectos",
            name="estado_modelo",
            field=models.CharField(
                choices=[("pendiente", "pendiente"), ("calculado", "calculado")],
                default="pendiente",
                max_length=20,
            ),
        ),
    ]
