# Generated by Django 5.1.7 on 2025-04-24 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0003_articulos_citados_articulos_resumen_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="investigador",
            name="departamento",
        ),
    ]
