# Generated by Django 5.1.7 on 2025-04-27 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0005_remove_investigador_avatar_url_investigador_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Materia",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "materias",
            },
        ),
        migrations.AddField(
            model_name="articulos",
            name="status",
            field=models.CharField(
                choices=[
                    ("EnProceso", "En proceso"),
                    ("Terminado", "Terminado"),
                    ("Aceptado", "Aceptado en revista"),
                    ("Publicado", "Publicado"),
                ],
                default="EnProceso",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="detlineas",
            name="reconocido",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="proyectos",
            name="status",
            field=models.CharField(
                choices=[
                    ("Proceso", "En proceso"),
                    ("Terminado", "Terminado"),
                    ("Instalado", "Instalado en sitio"),
                ],
                default="Pendiente",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="DetClase",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "investigador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.investigador",
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.materia",
                    ),
                ),
            ],
            options={
                "db_table": "det_clase",
                "unique_together": {("investigador", "materia")},
            },
        ),
    ]
