# Generated by Django 5.1.7 on 2025-04-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0006_materia_articulos_status_detlineas_reconocido_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estudiante",
            name="status",
            field=models.CharField(
                choices=[
                    ("Activo", "Activo"),
                    ("Abandonó", "Abandonó"),
                    ("Egresado", "Egresado"),
                    ("Titulado", "Titulado"),
                ],
                default="Activo",
                max_length=50,
            ),
        ),
    ]
