# Generated by Django 5.1.7 on 2025-04-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0007_alter_estudiante_status"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DetClase",
            new_name="DetMateria",
        ),
        migrations.RemoveField(
            model_name="deteventos",
            name="asunto",
        ),
        migrations.AddField(
            model_name="deteventos",
            name="es_principal",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name="detmateria",
            table="det_materia",
        ),
    ]
