# Generated by Django 5.1.7 on 2025-04-27 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "gestion",
            "0008_rename_detclase_detmateria_remove_deteventos_asunto_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deteventos",
            name="es_principal",
        ),
    ]
