# Generated by Django 5.1.7 on 2025-04-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0009_remove_deteventos_es_principal"),
    ]

    operations = [
        migrations.AddField(
            model_name="deteventos",
            name="asunto",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
