from .investigador_viewset import InvestigadorViewSet
from .nivel_snii_viewset import NivelSniiViewSet
from .snii_viewset import SniiViewSet
from .lineas_viewset import LineasViewSet
from .det_lineas_viewset import DetLineasViewSet
from .articulos_viewset import ArticulosViewSet
from .det_art_viewset import DetArtViewSet
from .tipo_evento_viewset import TipoEventoViewSet
from .eventos_viewset import EventosViewSet
from .det_eventos_viewset import DetEventosViewSet
from .herramientas_viewset import HerramientasViewSet
from .det_herr_viewset import DetHerrViewSet
from .proyectos_viewset import ProyectosViewSet
from .det_proy_viewset import DetProyViewSet
from .carreras_viewset import CarrerasViewSet
from .tipo_estudiante_viewset import TipoEstudianteViewSet
from .estudiantes_viewset import EstudiantesViewSet
from .usuarios_viewset import UsuariosViewSet
from .dashboard_view import dashboard_data
from .educacion_viewset import EducacionViewSet
from .materia_viewset import MateriaViewSet
from .det_materia_viewset import DetMateriaViewset
from .upload_seeder import UploadSeeder
